config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  get 'home/index'
  
  resources :documents, only: [:index, :new, :create, :destroy]
   root "documents#index"

end

app/models/document.rb
class Document < ActiveRecord::Base
    
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   
   belongs_to :user
   
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :documents
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
         
         validates_format_of :email, :with => (/^([^@\s]+)@((gmail)\.+[a-z]{2,})$/i), :multiline => true
         validates_presence_of :first_name
         validates_presence_of :last_name
         validates_presence_of :username
         validates :phone ,:presence => true,
                   :numericality => true,
                   :length => { :minimum => 11, :maximum => 11 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
   def index
      @documents = Document.where(user_id: current_user)
   end
   
   def new
      @document = current_user.documents.build
   end
   
   def create
      @document = current_user.documents.build(document_params)
      
      if @document.save
         redirect_to documents_path, notice: "The document #{@document.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @document = document.find(params[:id])
      @document.destroy
      redirect_to documents_path, notice:  "The document #{@document.name} has been deleted."
   end
   
   private
      def document_params
      params.require(:document).permit(:name, :content, :attachment)
      end
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New Document", new_document_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Content</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @documents.each do |document| %>
         
         <tr>
            <td><%= document.name %></td>
            <td><%= document.content %></td>
            <td><%= link_to "Download Document", document.attachment_url %></td>
            <td><%= button_to "Delete",  document, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{document.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>

app/views/documents/new.html.erb
<% if !@document.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @document.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @document, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :content %>
      <%= f.text_field :content %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container" >
  
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
   <%= link_to 'Edit profile', edit_user_registration_path %> |
   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
 <% else %>
   <%= link_to "Sign up", new_user_registration_path  %> |
   <%= link_to "Login", new_user_session_path %>
 <% end %>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%= yield %>
  </div>
</body>
</html>